package com.rababodrif.bank2app.models;

public enum HistoryEventType {
    TRANSACTION_CREATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSFER_CREATED,
    TRANSFER_COMPLETED,
    TRANSFER_FAILED,
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,
    BALANCE_UPDATED,
    TRANSFER_EXECUTED
}